server.port: 8090

spring:
  application-name: sender-app
  kafka:
    bootstrap-servers: localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      document-checks:
        v1: demo-documents-v1

logging:
  level:
    root: INFO
    org.apache.kafka.common.utils: WARN
    org.apache.kafka.clients: WARN